services:
  db:
    image: postgres:16
    container_name: flask_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - flask-network

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8081:5050"
    environment:
      FLASK_APP: app.app
      FLASK_ENV: production
    depends_on:
      - db
    networks:
      - flask-network

#  nginx:
#    image: nginx:latest
#    container_name: flask-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
##    depends_on:
##      - web
#    networks:
#      - flask-network

volumes:
  postgres_data:

networks:
  flask-network:
    driver: bridge